#!/bin/bash
# Показати всі доступні команди для навчання

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

echo "=== Доступні команди навчання Moyva ==="
echo ""

echo "🚀 ЗАПУСК НАВЧАННЯ:"
echo "  ./tools/ai/train_simple.sh [арени] [швидкість] [макс_кроки]"
echo "    Приклад: ./tools/ai/train_simple.sh 8 5.0 1000000"
echo ""
echo "  ./tools/ai/train_parallel.sh"
echo "    Використовує налаштування з файлу скрипта"
echo ""
echo "  python3 tools/ai/moyva_train.py train --arenas 8 --time-scale 5.0 --headless"
echo "    Прямий запуск через Python"
echo ""

echo "📊 ПЕРЕВІРКА ПРОГРЕСУ:"
echo "  ./tools/ai/check_progress.sh"
echo "    Показує поточний сценарій та прогрес навчання"
echo ""

echo "🔧 КОНФІГУРАЦІЯ:"
echo "  ./tools/ai/quick_test.sh"
echo "    Перевіряє конфігурацію навчання"
echo ""
echo "  vim Assets/Moyva/Presets/AI/MoyvaTrainingConfig.json"
echo "    Редагувати конфігурацію навчання"
echo ""

echo "🏗️  BUILDS:"
echo "  ./tools/ai/train_unity_editor.sh"
echo "    Побудувати training player через Unity"
echo ""

echo "📖 ДОКУМЕНТАЦІЯ:"
echo "  cat tools/ai/TRAINING_GUIDE.md"
echo "    Повна документація з навчання"
echo ""

echo "🐍 PYTHON ML-AGENTS:"
echo "  pip3 install -r tools/ai/requirements-training.txt"
echo "    Встановити залежності для навчання"
echo ""
echo "  python3 -m mlagents.trainers.learn --help"
echo "    Довідка по ML-Agents trainer"
echo ""

echo "📋 ПАРАМЕТРИ COMMAND LINE:"
echo "  --arenas N              Кількість паралельних арен (1-16)"
echo "  --time-scale X          Швидкість навчання (0.1-20.0)"
echo "  --max-steps N           Максимальна кількість кроків"
echo "  --headless              Режим без графіки (швидше)"
echo "  --visual                Візуальний режим (для налагодження)"
echo "  --world-size N          Розмір світу (12-128)"
echo "  --stage N               Етап навчального плану (0-8)"
echo "  --seed N                Seed для відтворюваності"
echo "  --run-id ID             Ідентифікатор запуску"
echo "  --resume                Продовження попереднього запуску"
echo ""

echo "🎯 СЦЕНАРІЇ НАВЧАННЯ:"
echo "  foundation-legal-setup  - Правильний початковий стан"
echo "  castle                  - Побудова замку"
echo "  production              - Ресурсне виробництво"
echo "  stable-economy          - Стабільна економіка"
echo "  recruitment             - Набір юнітів"
echo "  movement-scouting       - Рух та розвідка"
echo "  combat-defense          - Бойові дії"
echo "  capture                 - Захват об'єктів"
echo "  full-game-autonomous    - Повна гра"
echo ""

echo "💡 ПОРАДИ:"
echo "  - Для тестування: --arenas 1 --time-scale 1.0 --visual"
echo "  - Для швидкості: --arenas 16 --time-scale 10.0 --headless"
echo "  - Для балансу: --arenas 8 --time-scale 5.0 --headless"
echo "  - Моніторинг: tail -f Results/MoyvaTraining/*/mlagents.log"
echo ""
