using Kruty1918.Moyva.GraphSystem.API;
using UnityEngine;

namespace Kruty1918.Moyva.Generator.Runtime.Nodes
{
    [NodeInfo("Route Point", "Utility", "Проміжна точка для укладання трас з'єднань. Пропускає будь-які дані далі без змін, але дозволяє вручну згинати лінії для кращої читабельності графа.")]
    public sealed class RoutePointNode : NodeBase
    {
        [SerializeField, HideInInspector] private bool _autoGenerated;

        public override string Title => "Route Point";
        public override string Category => "Utility";

        public bool AutoGenerated
        {
            get => _autoGenerated;
            set => _autoGenerated = value;
        }

        public override PortDefinition[] Inputs => new[]
        {
            PortDefinition.Input<object>("In")
        };

        public override PortDefinition[] Outputs => new[]
        {
            PortDefinition.Output<object>("Out")
        };

        public override NodeOutput Execute(object[] inputs, NodeContext context)
        {
            var value = (inputs != null && inputs.Length > 0) ? inputs[0] : null;
            return NodeOutput.Success(value);
        }
    }
}